[package]
name = "dolphin-rs"
version = "0.1.0"
authors = ["Evan Maddock <maddock.evan@vivaldi.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
confy = "^0.4.0"
directories = "^3.0.0"
log = "^0.4.0"
serde = {version = "^1.0", features = ["derive"]}
simplelog = "^0.8.0"
