[package]
name = "dolphin-rs"
version = "2.1.1"
authors = ["Evan Maddock <maddock.evan@vivaldi.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
confy = "0.4.0"
err-derive = "0.2.4"
lazy_static = "1.4.0"
linemux = "0.1.2"
rcon = "0.3.1"
regex = "1.4.2"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0"
serenity = { version = "0.9.1" }
tokio = { version = "0.2.22", features = ["sync", "time"] }
tracing = "0.1.21"
tracing-subscriber = "0.2.15"
warp = "0.2"

[profile.dev]
# Let's speed up compilation and maybe reduce dev binary size a bunch.
debug = 0

