[package]
name = "dolphin-rs"
version = "2.0.0"
authors = ["Evan Maddock <maddock.evan@vivaldi.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33.2"
confy = "^0.4.0"
directories = "^3.0.0"
err-derive = "^0.2.4"
lazy_static = "^1.4.0"
linemux = "^0.1.2"
rcon = "^0.3.0"
regex = "^1.4.0"
serde = { version = "^1.0", features = ["derive"] }
serenity = { version = "^0.9.0" }
tokio = { version = "^0.2.22", features = ["time"] }
tracing = "^0.1.0"
tracing-subscriber = "^0.2.0"

